
STANDARD_TASKS = [
    # ELEMEN 1 – KEPEMIMPINAN DAN KOMITMEN
    {"code": "1.1", "title": "KOMITMEN HSSE MELALUI KEPEMIMPINAN", "category": "ELEMEN 1 – KEPEMIMPINAN DAN KOMITMEN"},

    # ELEMEN 2 – TUJUAN KEBIJAKAN HSSE DAN STRATEGI
    {"code": "2.1", "title": "DOKUMEN KEBIJAKAN HSSE", "category": "ELEMEN 2 – TUJUAN KEBIJAKAN HSSE DAN STRATEGI"},
    {"code": "2.2", "title": "SASARAN STRATEGIS HSSE BERKALA (TAHUNAN)", "category": "ELEMEN 2 – TUJUAN KEBIJAKAN HSSE DAN STRATEGI"},

    # ELEMEN 3 – ORGANISASI, TANGGUNG JAWAB, SUMBER DAYA, STANDAR DAN DOKUMENTASI
    {"code": "3.1", "title": "STRUKTUR ORGANISASI UNTUK PENGELOLAAN HSSE", "category": "ELEMEN 3 – ORGANISASI, TANGGUNG JAWAB, SUMBER DAYA, STANDAR DAN DOKUMENTASI"},
    {"code": "3.2", "title": "PELATIHAN HSSE UNTUK PARA MANAJER, PENYELIA", "category": "ELEMEN 3 – ORGANISASI, TANGGUNG JAWAB, SUMBER DAYA, STANDAR DAN DOKUMENTASI"},
    {"code": "3.3", "title": "PELATIHAN HSSE UMUM (PADA SELURUH PEKERJA DAN PIHAK TERKAIT)", "category": "ELEMEN 3 – ORGANISASI, TANGGUNG JAWAB, SUMBER DAYA, STANDAR DAN DOKUMENTASI"},
    {"code": "3.4", "title": "PEMENUHAN KOMPETENSI HSSE", "category": "ELEMEN 3 – ORGANISASI, TANGGUNG JAWAB, SUMBER DAYA, STANDAR DAN DOKUMENTASI"},
    {"code": "3.5", "title": "PENGELOLAAN HSSE KONTRAKTOR", "category": "ELEMEN 3 – ORGANISASI, TANGGUNG JAWAB, SUMBER DAYA, STANDAR DAN DOKUMENTASI"},
    {"code": "3.6", "title": "PERATURAN DAN STANDAR HSSE", "category": "ELEMEN 3 – ORGANISASI, TANGGUNG JAWAB, SUMBER DAYA, STANDAR DAN DOKUMENTASI"},

    # ELEMEN 4 – MANAJEMEN RISIKO
    {"code": "4.1", "title": "PENILAIAN DAN PENGENDALIAN RISIKO", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},
    {"code": "4.2", "title": "BAHAYA TERHADAP KESEHATAN KERJA", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},
    {"code": "4.3", "title": "BAHAYA TERHADAP KESELAMATAN KERJA", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},
    {"code": "4.4", "title": "BAHAYA KEGIATAN LOGISTIK", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},
    {"code": "4.5", "title": "BAHAYA TERHADAP LINGKUNGAN", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},
    {"code": "4.6", "title": "BAHAYA TERHADAP KEAMANAN", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},
    {"code": "4.7", "title": "BAHAYA TERHADAP ASPEK SOSIAL", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},
    {"code": "4.8", "title": "ALAT PELINDUNG DIRI (APD)", "category": "ELEMEN 4 – MANAJEMEN RISIKO"},

    # ELEMEN 5 – PERENCANAAN DAN PROSEDUR
    {"code": "5.1", "title": "MANUAL OPERASI HSSE", "category": "ELEMEN 5 – PERENCANAAN DAN PROSEDUR"},
    {"code": "5.2", "title": "KEHANDALAN INFRAKSTRUKTUR DAN PERALATAN", "category": "ELEMEN 5 – PERENCANAAN DAN PROSEDUR"},
    {"code": "5.3", "title": "MANAJEMEN PERUBAHAN", "category": "ELEMEN 5 – PERENCANAAN DAN PROSEDUR"},
    {"code": "5.4", "title": "RENCANA TANGGAP DARURAT", "category": "ELEMEN 5 – PERENCANAAN DAN PROSEDUR"},

    # ELEMEN 6 – IMPLEMENTASI DAN PEMANTAUAN KINERJA
    {"code": "6.1", "title": "IMPLEMENTASI SISTEM MANAJEMEN HSSE DAN PEMANTAUAN KINERJA SECARA AKTIF", "category": "ELEMEN 6 – IMPLEMENTASI DAN PEMANTAUAN KINERJA"},
    {"code": "6.2", "title": "INDIKATOR KINERJA HSSE", "category": "ELEMEN 6 – IMPLEMENTASI DAN PEMANTAUAN KINERJA"},
    {"code": "6.3", "title": "PEMANTAUAN KINERJA HSSE", "category": "ELEMEN 6 – IMPLEMENTASI DAN PEMANTAUAN KINERJA"},
    {"code": "6.4", "title": "INVESTIGASI DAN TINDAKLANJUT INSIDEN HSSE", "category": "ELEMEN 6 – IMPLEMENTASI DAN PEMANTAUAN KINERJA"},
    {"code": "6.5", "title": "INSIDEN YANG HARUS DILAPORKAN SESUAI UNDANG-UNDANG DAN CATATAN KETIDAKPATUHAN", "category": "ELEMEN 6 – IMPLEMENTASI DAN PEMANTAUAN KINERJA"},

    # ELEMEN 7 – AUDIT DAN TINJAUAN
    {"code": "7.1", "title": "AUDIT", "category": "ELEMEN 7 – AUDIT DAN TINJAUAN"},
    {"code": "7.2", "title": "TINJAUAN MANAJEMEN DAN TINDAKLANJUT", "category": "ELEMEN 7 – AUDIT DAN TINJAUAN"},

    # ELEMEN 8 – MANAJEMEN K3LL – PENCAPAIAN LAINNYA
    {"code": "8.1", "title": "SERTIFIKASI SISTEM MANAJEMEN HSSE", "category": "ELEMEN 8 – MANAJEMEN K3LL – PENCAPAIAN LAINNYA"},
    {"code": "8.2", "title": "KEANGGOTAAN ASOSIASI", "category": "ELEMEN 8 – MANAJEMEN K3LL – PENCAPAIAN LAINNYA"},
]
